MODEL:
  TYPE: mamba
  NAME: defocus_mamba_large
  PRETRAINED: path/to/22k/pretrained/ckpt
  depth: 48
  drop_path_rate: 0.7
  min_drop_path_rate: 0.1
  use_scheduled_drop_path: True
  head_type: IN22kto1k_cls
  use_aux_loss: True
  use_rope: True
  MAMBA:
    intermediate_size: 2048
    conv_kernel: 4
    group_norm_size: 64
    delta_scale_factor: 2.0
    rope_scale_factor: 4.0
TRAIN:
  EPOCHS: 20
  WARMUP_EPOCHS: 2
  BASE_LR: 2e-5
  CLIP_GRAD: 10.0
DATA:
  DATA_PATH: path/to/imagenet1k
  BATCH_SIZE: 32
  IMG_SIZE: 384
AUG:
  AUTO_AUGMENT: None
  COLOR_JITTER: 0.0
  MIXUP_PROB: 0.5
  MIXUP_SWITCH_PROB: 0.0
  REPROB: 0.0
  use_repeated_aug: False
bfloat16: True
